name: Python Job Demo
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch: 
jobs: 
  Run-Python:
  
    runs-on: self-hosted

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Run Python script
        run: python job.py