name: Artifact Demo
on:
  workflow_dispatch:
  push:

jobs:
  Build-and-Store:
    runs-on: self-hosted
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Creer un fichier texte avec redirection
        run: echo "Ceci est un rapport genere par la CI le $(Get-Date)" > output.txt

      - name: Sauvegarder localement l'artefact sur la machine
        run: |
          New-Item -ItemType Directory -Path "C:\artifacts" -Force
          Copy-Item output.txt -Destination "C:\artifacts\rapport-execution.txt"
          Write-Host "Fichier sauvegarde dans C:\artifacts\rapport-execution.txt"